openapi: "3.0.0"
info:
  title: Redact API
  description: An API for redacting sensitive data from CSV, Excel and JSON files
  version: "1.0.0"
servers:
  - url: <http://localhost:6000/>
paths:
  /api/process_csv:
    post:
      summary: Process a CSV file and redact sensitive data
      description: This endpoint allows users to upload a CSV file and specify a redaction method to remove sensitive data from the file. The redacted file can be downloaded in the same format as the original file. The endpoint also supports synthetic data generation to replace sensitive data with realistic but fake data.
      operationId: processCsvFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The CSV file to be redacted.
                redaction_method:
                  type: string
                  enum: [fixed_string, random_value, hash]
                  description: The method to be used for redacting sensitive data from the file.
                synthetic_data_generation:
                  type: string
                  enum: [true, false]
                  description: Whether to generate synthetic data to replace sensitive data in the file.
      responses:
        "200":
          description: Success
          content:
            text/csv:
              schema:
                type: string
                format: binary
        "400":
          description: Bad request
  /api/process_excel:
    post:
      summary: Process an Excel file and redact sensitive data
      description: This endpoint allows users to upload an Excel file and specify a redaction method to remove sensitive data from the file. The redacted file can be downloaded in the same format as the original file. The endpoint also supports synthetic data generation to replace sensitive data with realistic but fake data.
      operationId: processExcelFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The Excel file to be redacted.
                redaction_method:
                  type: string
                  enum: [fixed_string, random_value, hash]
                  description: The method to be used for redacting sensitive data from the file.
                synthetic_data_generation:
                  type: string
                  enum: [true, false]
                  description: Whether to generate synthetic data to replace sensitive data in the file.
      responses:
        "200":
          description: Success
          content:
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                type: string
                format: binary
        "400":
          description: Bad request
  /api/process_json:
    post:
      summary: Process a JSON file and redact sensitive data
      description: This endpoint allows users to upload a JSON file and specify a redaction method to remove sensitive data from the file. The redacted file can be downloaded in the same format as the original file. The endpoint also supports synthetic data generation to replace sensitive data with realistic but fake data.
      operationId: processJsonFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The JSON file to be redacted.
                redaction_method:
                  type: string
                  enum: [fixed_string, random_value, hash]
                  description: The method to be used for redacting sensitive data from the file.
                synthetic_data_generation:
                  type: string
                  enum: [true, false]
                  description: Whether to generate synthetic data to replace sensitive data in the file.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
                format: binary
        "400":
          description: Bad request
